# Generated by Django 5.0.1 on 2024-01-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('ForEnquiry', 'For Enquiry'), ('PlaceOrder', 'Place Order'), ('Return', 'Return')], max_length=20),
        ),
    ]
